In [1]:
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving dataset_ecommerce_sales_final_project.csv to dataset_ecommerce_sales_final_project.csv

In [3]:
df = pd.read_csv("dataset_ecommerce_sales_final_project.csv")

df

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
0,ORD-0001,2026-05-03,Ali,Trabzon,Kitap,Roman,Standart,Kredi Kartı,470,1,0.05,446.5,5,Tamamlandı
1,ORD-0002,2026-06-07,Ceren,Konya,Moda,Gömlek,Silver,Kredi Kartı,1180,2,0.05,2242.0,3,Tamamlandı
2,ORD-0003,2026-05-25,Zeynep,Eskişehir,Spor,Dambıl Seti,Standart,Havale,1810,1,0.00,1810.0,3,Tamamlandı
3,ORD-0004,2026-05-19,Tuna,Konya,Oyuncak,Araba Seti,Silver,Havale,490,1,0.10,441.0,5,Tamamlandı
4,ORD-0005,2026-05-25,Ceren,Bursa,Ev & Yaşam,Masa Lambası,Standart,Kapıda Ödeme,260,1,0.05,247.0,2,Tamamlandı
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ORD-0096,2026-06-07,Derya,Adana,Market,Bitki Çayı,Standart,Havale,320,3,0.00,960.0,2,Tamamlandı
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
97,ORD-0098,2026-06-26,Emre,Adana,Market,Zeytinyağı,Standart,Banka Kartı,540,1,0.05,513.0,4,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı
99,ORD-0100,2026-06-13,Efe,Eskişehir,Kitap,Kişisel Gelişim Kitabı,Standart,Havale,100,1,0.00,100.0,2,Tamamlandı

In [4]:
df.head(20)

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
0,ORD-0001,2026-05-03,Ali,Trabzon,Kitap,Roman,Standart,Kredi Kartı,470,1,0.05,446.5,5,Tamamlandı
1,ORD-0002,2026-06-07,Ceren,Konya,Moda,Gömlek,Silver,Kredi Kartı,1180,2,0.05,2242.0,3,Tamamlandı
2,ORD-0003,2026-05-25,Zeynep,Eskişehir,Spor,Dambıl Seti,Standart,Havale,1810,1,0.00,1810.0,3,Tamamlandı
3,ORD-0004,2026-05-19,Tuna,Konya,Oyuncak,Araba Seti,Silver,Havale,490,1,0.10,441.0,5,Tamamlandı
4,ORD-0005,2026-05-25,Ceren,Bursa,Ev & Yaşam,Masa Lambası,Standart,Kapıda Ödeme,260,1,0.05,247.0,2,Tamamlandı
5,ORD-0006,2026-05-11,Emre,Ankara,Kitap,Kişisel Gelişim Kitabı,Silver,Banka Kartı,160,1,0.05,152.0,2,Tamamlandı
6,ORD-0007,2026-06-19,Ayşe,Eskişehir,Elektronik,Powerbank,Silver,Banka Kartı,1270,4,0.05,4826.0,5,Tamamlandı
7,ORD-0008,2026-06-01,Derya,Eskişehir,Oyuncak,Peluş Oyuncak,Gold,Kapıda Ödeme,670,1,0.10,603.0,4,Tamamlandı
8,ORD-0009,2026-05-09,İrem,Muğla,Elektronik,Akıllı Saat,Standart,Kapıda Ödeme,1200,2,0.00,2400.0,3,Tamamlandı
9,ORD-0010,2026-06-08,Buse,Muğla,Elektronik,Bluetooth Kulaklık,Standart,Havale,3080,1,0.00,3080.0,5,Tamamlandı
10,ORD-0011,2026-05-28,Elif,Eskişehir,Market,Kahve,Gold,Kapıda Ödeme,560,1,0.10,504.0,2,Tamamlandı
11,ORD-0012,2026-06-02,Mina,Antalya,Elektronik,Telefon Kılıfı,Silver,Banka Kartı,3410,3,0.10,9207.0,2,Tamamlandı
12,ORD-0013,2026-05-08,Barış,Eskişehir,Elektronik,Akıllı Saat,Silver,Havale,2100,3,0.10,5670.0,3,Tamamlandı
13,ORD-0014,2026-05-09,Kaan,Adana,Oyuncak,Peluş Oyuncak,Silver,Kapıda Ödeme,450,1,0.10,405.0,2,Tamamlandı
14,ORD-0015,2026-06-15,Mert,Trabzon,Market,Atıştırmalık,Standart,Kapıda Ödeme,250,3,0.00,750.0,2,Tamamlandı
15,ORD-0016,2026-06-05,Deniz,Eskişehir,Market,Zeytinyağı,Standart,Banka Kartı,380,2,0.00,760.0,2,Tamamlandı
16,ORD-0017,2026-06-01,Burak,Bursa,Elektronik,Bluetooth Kulaklık,Gold,Banka Kartı,1150,4,0.15,3910.0,1,Tamamlandı
17,ORD-0018,2026-05-28,Efe,Ankara,Spor,Su Matarası,Silver,Kapıda Ödeme,1530,1,0.05,1453.5,3,Tamamlandı
18,ORD-0019,2026-05-07,Deniz,Eskişehir,Kozmetik,Güneş Kremi,Standart,Banka Kartı,860,5,0.00,4300.0,2,Tamamlandı
19,ORD-0020,2026-06-25,Eylül,Ankara,Moda,Çanta,Silver,Kredi Kartı,470,1,0.05,446.5,1,Tamamlandı

In [5]:
df.tail(20)

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
80,ORD-0081,2026-06-25,Can,Muğla,Moda,Gömlek,Silver,Kapıda Ödeme,660,1,0.05,627.0,4,İptal
81,ORD-0082,2026-05-16,Aslı,Bursa,Ev & Yaşam,Kupa Seti,Standart,Kapıda Ödeme,790,3,0.00,2370.0,3,İptal
82,ORD-0083,2026-06-20,Tuna,Konya,Moda,Çanta,Silver,Banka Kartı,320,2,0.05,608.0,4,İptal
83,ORD-0084,2026-05-01,Arda,Adana,Ev & Yaşam,Masa Lambası,Standart,Banka Kartı,410,4,0.05,1558.0,4,Tamamlandı
84,ORD-0085,2026-06-24,Selin,Konya,Kozmetik,Parfüm,Standart,Kapıda Ödeme,230,3,0.00,690.0,2,Tamamlandı
85,ORD-0086,2026-06-17,Mehmet,Antalya,Market,Granola,Standart,Kapıda Ödeme,700,1,0.00,700.0,2,İptal
86,ORD-0087,2026-05-24,Kerem,İstanbul,Market,Kahve,Gold,Banka Kartı,380,2,0.15,646.0,4,Tamamlandı
87,ORD-0088,2026-05-16,Onur,Konya,Moda,Çanta,Standart,Banka Kartı,1130,3,0.05,3220.5,3,Tamamlandı
88,ORD-0089,2026-05-11,Mehmet,Antalya,Moda,Ceket,Gold,Kapıda Ödeme,960,2,0.10,1728.0,2,Tamamlandı
89,ORD-0090,2026-05-25,Eylül,Antalya,Market,Bitki Çayı,Silver,Kapıda Ödeme,270,4,0.05,1026.0,3,Tamamlandı
90,ORD-0091,2026-06-06,Eylül,Konya,Elektronik,Powerbank,Gold,Kredi Kartı,2190,2,0.10,3942.0,3,Tamamlandı
91,ORD-0092,2026-05-13,Mina,Eskişehir,Market,Granola,Silver,Havale,670,4,0.05,2546.0,4,Tamamlandı
92,ORD-0093,2026-06-16,Can,Adana,Kitap,Ajanda,Silver,Kredi Kartı,410,4,0.05,1558.0,3,Tamamlandı
93,ORD-0094,2026-06-28,Ceren,Eskişehir,Market,Zeytinyağı,Standart,Banka Kartı,610,1,0.00,610.0,2,Tamamlandı
94,ORD-0095,2026-06-18,Deniz,Adana,Moda,Çanta,Gold,Kapıda Ödeme,1750,1,0.10,1575.0,3,İade
95,ORD-0096,2026-06-07,Derya,Adana,Market,Bitki Çayı,Standart,Havale,320,3,0.00,960.0,2,Tamamlandı
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
97,ORD-0098,2026-06-26,Emre,Adana,Market,Zeytinyağı,Standart,Banka Kartı,540,1,0.05,513.0,4,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı
99,ORD-0100,2026-06-13,Efe,Eskişehir,Kitap,Kişisel Gelişim Kitabı,Standart,Havale,100,1,0.00,100.0,2,Tamamlandı

In [6]:
df.shape

(100, 14)

In [7]:
df.columns

Index(['siparis_id', 'siparis_tarihi', 'musteri_adi', 'sehir', 'kategori',
       'urun', 'uyelik_tipi', 'odeme_yontemi', 'urun_fiyati', 'adet',
       'indirim_orani', 'toplam_tutar', 'kargo_suresi_gun', 'siparis_durumu'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   siparis_id        100 non-null    object
 1   siparis_tarihi    100 non-null    object
 2   musteri_adi       100 non-null    object
 3   sehir             100 non-null    object
 4   kategori          100 non-null    object
 5   urun              100 non-null    object
 6   uyelik_tipi       100 non-null    object
 7   odeme_yontemi     100 non-null    object
 8   urun_fiyati       100 non-null    int64
 9   adet              100 non-null    int64
 10  indirim_orani     100 non-null    float64
 11  toplam_tutar      100 non-null    float64
 12  kargo_suresi_gun  100 non-null    int64
 13  siparis_durumu    100 non-null    object
dtypes: float64(2), int64(3), object(9)
memory usage: 11.1+ KB

In [9]:
df.describe()

       urun_fiyati        adet  indirim_orani  toplam_tutar  kargo_suresi_gun
count   100.000000  100.000000     100.000000    100.000000        100.000000
mean    931.100000    2.000000       0.046000   1758.780000          2.920000
std     736.343539    1.214392       0.041243   1854.705844          1.203362
min     100.000000    1.000000       0.000000    100.000000          1.000000
25%     440.000000    1.000000       0.000000    606.750000          2.000000
50%     695.000000    1.500000       0.050000   1173.000000          3.000000
75%    1185.000000    3.000000       0.050000   2240.500000          4.000000
max    3410.000000    5.000000       0.150000  10800.000000          7.000000

**Genel İçgörü**


*   Ortalama sipariş tutarı yaklaşık 1759 TL'dir.
*   Müşterilerin harcama tutarları arasında belirgin farklar bulunmaktadır.


*   Kargo süreleri genel olarak kısa görünmektedir. Ancak sipariş tutarları birbirinden oldukça farklıdır.
*  Veri seti, farklı müşteri gruplarının olduğunu göstermektedir. Bu nedenle müşterileri segmentlere ayırarak analiz yapmak daha faydalı olabilir.

In [11]:
df["toplam_tutar"].mean()

np.float64(1758.78)

In [12]:
df["toplam_tutar"].median()

1173.0

In [14]:
print("En dusuk siparis tutari:", df["toplam_tutar"].min())
print("En yuksek siparis tutari:", df["toplam_tutar"].max())

En dusuk siparis tutari: 100.0
En yuksek siparis tutari: 10800.0

In [21]:
tamamlanan_siparisler = df[df["siparis_durumu"] == "Tamamlandı"]

toplam_ciro = tamamlanan_siparisler["toplam_tutar"].sum()

print("Toplam Ciro:", toplam_ciro)

Toplam Ciro: 158271.5

In [22]:
tamamlanma_orani= (df["siparis_durumu"] == "Tamamlandı").mean() *100

print("Tamamlanan Siparis Orani:", tamamlanma_orani)

Tamamlanan Siparis Orani: 89.0

In [29]:
df[df["toplam_tutar"] > 1000]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
1,ORD-0002,2026-06-07,Ceren,Konya,Moda,Gömlek,Silver,Kredi Kartı,1180,2,0.05,2242.0,3,Tamamlandı
2,ORD-0003,2026-05-25,Zeynep,Eskişehir,Spor,Dambıl Seti,Standart,Havale,1810,1,0.00,1810.0,3,Tamamlandı
6,ORD-0007,2026-06-19,Ayşe,Eskişehir,Elektronik,Powerbank,Silver,Banka Kartı,1270,4,0.05,4826.0,5,Tamamlandı
8,ORD-0009,2026-05-09,İrem,Muğla,Elektronik,Akıllı Saat,Standart,Kapıda Ödeme,1200,2,0.00,2400.0,3,Tamamlandı
9,ORD-0010,2026-06-08,Buse,Muğla,Elektronik,Bluetooth Kulaklık,Standart,Havale,3080,1,0.00,3080.0,5,Tamamlandı
11,ORD-0012,2026-06-02,Mina,Antalya,Elektronik,Telefon Kılıfı,Silver,Banka Kartı,3410,3,0.10,9207.0,2,Tamamlandı
12,ORD-0013,2026-05-08,Barış,Eskişehir,Elektronik,Akıllı Saat,Silver,Havale,2100,3,0.10,5670.0,3,Tamamlandı
16,ORD-0017,2026-06-01,Burak,Bursa,Elektronik,Bluetooth Kulaklık,Gold,Banka Kartı,1150,4,0.15,3910.0,1,Tamamlandı
17,ORD-0018,2026-05-28,Efe,Ankara,Spor,Su Matarası,Silver,Kapıda Ödeme,1530,1,0.05,1453.5,3,Tamamlandı
18,ORD-0019,2026-05-07,Deniz,Eskişehir,Kozmetik,Güneş Kremi,Standart,Banka Kartı,860,5,0.00,4300.0,2,Tamamlandı
20,ORD-0021,2026-05-31,Burak,İzmir,Elektronik,Kablosuz Mouse,Gold,Kapıda Ödeme,3000,4,0.10,10800.0,4,Tamamlandı
21,ORD-0022,2026-05-10,Burak,Adana,Market,Atıştırmalık,Standart,Havale,330,5,0.00,1650.0,4,Tamamlandı
22,ORD-0023,2026-05-04,İrem,Muğla,Moda,Sneaker,Silver,Kredi Kartı,1150,2,0.10,2070.0,4,Tamamlandı
23,ORD-0024,2026-06-09,Mehmet,Muğla,Oyuncak,Puzzle,Standart,Kapıda Ödeme,940,2,0.05,1786.0,1,Tamamlandı
24,ORD-0025,2026-05-09,Kaan,Bursa,Kitap,Çocuk Kitabı,Standart,Havale,350,4,0.00,1400.0,2,Tamamlandı
30,ORD-0031,2026-05-14,Kaan,İstanbul,Ev & Yaşam,Kupa Seti,Standart,Banka Kartı,1240,1,0.00,1240.0,2,Tamamlandı
31,ORD-0032,2026-05-16,Eylül,İzmir,Kitap,Kişisel Gelişim Kitabı,Standart,Banka Kartı,490,3,0.00,1470.0,5,Tamamlandı
34,ORD-0035,2026-06-23,Emre,Konya,Kozmetik,Nemlendirici,Standart,Havale,1060,4,0.00,4240.0,4,Tamamlandı
37,ORD-0038,2026-05-20,İrem,Ankara,Kozmetik,Güneş Kremi,Silver,Havale,1150,4,0.05,4370.0,1,Tamamlandı
40,ORD-0041,2026-06-18,Deniz,Ankara,Ev & Yaşam,Yastık,Silver,Havale,1380,1,0.05,1311.0,4,Tamamlandı
42,ORD-0043,2026-05-15,Elif,Ankara,Spor,Koşu Taytı,Silver,Kapıda Ödeme,1340,1,0.10,1206.0,3,Tamamlandı
43,ORD-0044,2026-06-18,Gizem,Trabzon,Elektronik,Akıllı Saat,Standart,Kapıda Ödeme,3250,1,0.00,3250.0,3,İptal
44,ORD-0045,2026-06-23,Yasemin,Adana,Kitap,Çocuk Kitabı,Standart,Havale,300,4,0.05,1140.0,2,Tamamlandı
45,ORD-0046,2026-05-21,Gizem,Bursa,Spor,Su Matarası,Standart,Kredi Kartı,1310,1,0.00,1310.0,2,Tamamlandı
46,ORD-0047,2026-05-27,Ayşe,Eskişehir,Elektronik,Akıllı Saat,Standart,Banka Kartı,1620,1,0.00,1620.0,2,Tamamlandı
47,ORD-0048,2026-05-23,Mert,Muğla,Oyuncak,Zeka Oyunu,Silver,Kapıda Ödeme,1370,2,0.05,2603.0,4,Tamamlandı
48,ORD-0049,2026-06-01,Ali,Adana,Oyuncak,Zeka Oyunu,Silver,Kapıda Ödeme,860,2,0.05,1634.0,5,Tamamlandı
49,ORD-0050,2026-06-07,Aslı,Trabzon,Moda,Çanta,Gold,Kredi Kartı,1370,3,0.10,3699.0,3,Tamamlandı
53,ORD-0054,2026-05-07,Aslı,İzmir,Spor,Dambıl Seti,Silver,Kredi Kartı,1590,4,0.05,6042.0,3,İade
54,ORD-0055,2026-06-23,Yasemin,Ankara,Market,Bitki Çayı,Standart,Banka Kartı,560,4,0.00,2240.0,4,Tamamlandı
55,ORD-0056,2026-05-28,Kaan,İstanbul,Elektronik,Telefon Kılıfı,Standart,Havale,3040,2,0.00,6080.0,4,Tamamlandı
57,ORD-0058,2026-05-21,Eylül,Adana,Kozmetik,Şampuan,Gold,Banka Kartı,1160,1,0.10,1044.0,3,Tamamlandı
60,ORD-0061,2026-05-06,Mert,Adana,Moda,Çanta,Silver,Banka Kartı,1010,3,0.05,2878.5,2,Tamamlandı
63,ORD-0064,2026-05-24,Elif,Bursa,Moda,Gömlek,Standart,Havale,1760,2,0.05,3344.0,1,Tamamlandı
66,ORD-0067,2026-05-16,Zeynep,Antalya,Kozmetik,Güneş Kremi,Standart,Kapıda Ödeme,760,2,0.00,1520.0,3,Tamamlandı
69,ORD-0070,2026-05-30,Mehmet,Antalya,Elektronik,Powerbank,Standart,Banka Kartı,2550,1,0.00,2550.0,2,Tamamlandı
70,ORD-0071,2026-06-22,Can,İzmir,Market,Bitki Çayı,Standart,Kredi Kartı,550,4,0.00,2200.0,3,Tamamlandı
71,ORD-0072,2026-05-18,İrem,Adana,Elektronik,Telefon Kılıfı,Gold,Kapıda Ödeme,2260,3,0.10,6102.0,7,Tamamlandı
73,ORD-0074,2026-06-07,Kerem,Adana,Market,Zeytinyağı,Standart,Kapıda Ödeme,480,3,0.00,1440.0,6,Tamamlandı
76,ORD-0077,2026-06-05,Can,İstanbul,Kozmetik,Parfüm,Silver,Havale,690,2,0.05,1311.0,3,Tamamlandı
77,ORD-0078,2026-05-01,Emre,İzmir,Kozmetik,Ruj,Silver,Kapıda Ödeme,280,5,0.05,1330.0,2,Tamamlandı
78,ORD-0079,2026-05-18,Kerem,Antalya,Elektronik,Bluetooth Kulaklık,Gold,Kapıda Ödeme,1860,1,0.10,1674.0,3,Tamamlandı
81,ORD-0082,2026-05-16,Aslı,Bursa,Ev & Yaşam,Kupa Seti,Standart,Kapıda Ödeme,790,3,0.00,2370.0,3,İptal
83,ORD-0084,2026-05-01,Arda,Adana,Ev & Yaşam,Masa Lambası,Standart,Banka Kartı,410,4,0.05,1558.0,4,Tamamlandı
87,ORD-0088,2026-05-16,Onur,Konya,Moda,Çanta,Standart,Banka Kartı,1130,3,0.05,3220.5,3,Tamamlandı
88,ORD-0089,2026-05-11,Mehmet,Antalya,Moda,Ceket,Gold,Kapıda Ödeme,960,2,0.10,1728.0,2,Tamamlandı
89,ORD-0090,2026-05-25,Eylül,Antalya,Market,Bitki Çayı,Silver,Kapıda Ödeme,270,4,0.05,1026.0,3,Tamamlandı
90,ORD-0091,2026-06-06,Eylül,Konya,Elektronik,Powerbank,Gold,Kredi Kartı,2190,2,0.10,3942.0,3,Tamamlandı
91,ORD-0092,2026-05-13,Mina,Eskişehir,Market,Granola,Silver,Havale,670,4,0.05,2546.0,4,Tamamlandı
92,ORD-0093,2026-06-16,Can,Adana,Kitap,Ajanda,Silver,Kredi Kartı,410,4,0.05,1558.0,3,Tamamlandı
94,ORD-0095,2026-06-18,Deniz,Adana,Moda,Çanta,Gold,Kapıda Ödeme,1750,1,0.10,1575.0,3,İade
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı

In [28]:
df[df["uyelik_tipi"] == "Gold"]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
7,ORD-0008,2026-06-01,Derya,Eskişehir,Oyuncak,Peluş Oyuncak,Gold,Kapıda Ödeme,670,1,0.10,603.0,4,Tamamlandı
10,ORD-0011,2026-05-28,Elif,Eskişehir,Market,Kahve,Gold,Kapıda Ödeme,560,1,0.10,504.0,2,Tamamlandı
16,ORD-0017,2026-06-01,Burak,Bursa,Elektronik,Bluetooth Kulaklık,Gold,Banka Kartı,1150,4,0.15,3910.0,1,Tamamlandı
20,ORD-0021,2026-05-31,Burak,İzmir,Elektronik,Kablosuz Mouse,Gold,Kapıda Ödeme,3000,4,0.10,10800.0,4,Tamamlandı
26,ORD-0027,2026-06-12,Tuna,Muğla,Market,Atıştırmalık,Gold,Havale,330,1,0.10,297.0,1,İptal
28,ORD-0029,2026-05-03,Ali,Konya,Moda,Ceket,Gold,Havale,1030,1,0.15,875.5,2,Tamamlandı
41,ORD-0042,2026-06-26,Yasemin,Ankara,Moda,Tişört,Gold,Banka Kartı,480,1,0.10,432.0,3,Tamamlandı
49,ORD-0050,2026-06-07,Aslı,Trabzon,Moda,Çanta,Gold,Kredi Kartı,1370,3,0.10,3699.0,3,Tamamlandı
57,ORD-0058,2026-05-21,Eylül,Adana,Kozmetik,Şampuan,Gold,Banka Kartı,1160,1,0.10,1044.0,3,Tamamlandı
71,ORD-0072,2026-05-18,İrem,Adana,Elektronik,Telefon Kılıfı,Gold,Kapıda Ödeme,2260,3,0.10,6102.0,7,Tamamlandı
78,ORD-0079,2026-05-18,Kerem,Antalya,Elektronik,Bluetooth Kulaklık,Gold,Kapıda Ödeme,1860,1,0.10,1674.0,3,Tamamlandı
86,ORD-0087,2026-05-24,Kerem,İstanbul,Market,Kahve,Gold,Banka Kartı,380,2,0.15,646.0,4,Tamamlandı
88,ORD-0089,2026-05-11,Mehmet,Antalya,Moda,Ceket,Gold,Kapıda Ödeme,960,2,0.10,1728.0,2,Tamamlandı
90,ORD-0091,2026-06-06,Eylül,Konya,Elektronik,Powerbank,Gold,Kredi Kartı,2190,2,0.10,3942.0,3,Tamamlandı
94,ORD-0095,2026-06-18,Deniz,Adana,Moda,Çanta,Gold,Kapıda Ödeme,1750,1,0.10,1575.0,3,İade
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı

In [30]:
df[df["kategori"] == "Elektronik"]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
6,ORD-0007,2026-06-19,Ayşe,Eskişehir,Elektronik,Powerbank,Silver,Banka Kartı,1270,4,0.05,4826.0,5,Tamamlandı
8,ORD-0009,2026-05-09,İrem,Muğla,Elektronik,Akıllı Saat,Standart,Kapıda Ödeme,1200,2,0.00,2400.0,3,Tamamlandı
9,ORD-0010,2026-06-08,Buse,Muğla,Elektronik,Bluetooth Kulaklık,Standart,Havale,3080,1,0.00,3080.0,5,Tamamlandı
11,ORD-0012,2026-06-02,Mina,Antalya,Elektronik,Telefon Kılıfı,Silver,Banka Kartı,3410,3,0.10,9207.0,2,Tamamlandı
12,ORD-0013,2026-05-08,Barış,Eskişehir,Elektronik,Akıllı Saat,Silver,Havale,2100,3,0.10,5670.0,3,Tamamlandı
16,ORD-0017,2026-06-01,Burak,Bursa,Elektronik,Bluetooth Kulaklık,Gold,Banka Kartı,1150,4,0.15,3910.0,1,Tamamlandı
20,ORD-0021,2026-05-31,Burak,İzmir,Elektronik,Kablosuz Mouse,Gold,Kapıda Ödeme,3000,4,0.10,10800.0,4,Tamamlandı
43,ORD-0044,2026-06-18,Gizem,Trabzon,Elektronik,Akıllı Saat,Standart,Kapıda Ödeme,3250,1,0.00,3250.0,3,İptal
46,ORD-0047,2026-05-27,Ayşe,Eskişehir,Elektronik,Akıllı Saat,Standart,Banka Kartı,1620,1,0.00,1620.0,2,Tamamlandı
50,ORD-0051,2026-05-22,Melis,Bursa,Elektronik,Powerbank,Standart,Kapıda Ödeme,860,1,0.00,860.0,3,Tamamlandı
55,ORD-0056,2026-05-28,Kaan,İstanbul,Elektronik,Telefon Kılıfı,Standart,Havale,3040,2,0.00,6080.0,4,Tamamlandı
56,ORD-0057,2026-06-23,Buse,Eskişehir,Elektronik,Telefon Kılıfı,Silver,Banka Kartı,490,1,0.05,465.5,2,Tamamlandı
64,ORD-0065,2026-06-18,Onur,İzmir,Elektronik,Kablosuz Mouse,Standart,Kredi Kartı,840,1,0.00,840.0,4,Tamamlandı
69,ORD-0070,2026-05-30,Mehmet,Antalya,Elektronik,Powerbank,Standart,Banka Kartı,2550,1,0.00,2550.0,2,Tamamlandı
71,ORD-0072,2026-05-18,İrem,Adana,Elektronik,Telefon Kılıfı,Gold,Kapıda Ödeme,2260,3,0.10,6102.0,7,Tamamlandı
78,ORD-0079,2026-05-18,Kerem,Antalya,Elektronik,Bluetooth Kulaklık,Gold,Kapıda Ödeme,1860,1,0.10,1674.0,3,Tamamlandı
90,ORD-0091,2026-06-06,Eylül,Konya,Elektronik,Powerbank,Gold,Kredi Kartı,2190,2,0.10,3942.0,3,Tamamlandı
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı

In [32]:
df[df["siparis_durumu"] == "Tamamlandı"]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
0,ORD-0001,2026-05-03,Ali,Trabzon,Kitap,Roman,Standart,Kredi Kartı,470,1,0.05,446.5,5,Tamamlandı
1,ORD-0002,2026-06-07,Ceren,Konya,Moda,Gömlek,Silver,Kredi Kartı,1180,2,0.05,2242.0,3,Tamamlandı
2,ORD-0003,2026-05-25,Zeynep,Eskişehir,Spor,Dambıl Seti,Standart,Havale,1810,1,0.00,1810.0,3,Tamamlandı
3,ORD-0004,2026-05-19,Tuna,Konya,Oyuncak,Araba Seti,Silver,Havale,490,1,0.10,441.0,5,Tamamlandı
4,ORD-0005,2026-05-25,Ceren,Bursa,Ev & Yaşam,Masa Lambası,Standart,Kapıda Ödeme,260,1,0.05,247.0,2,Tamamlandı
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ORD-0096,2026-06-07,Derya,Adana,Market,Bitki Çayı,Standart,Havale,320,3,0.00,960.0,2,Tamamlandı
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
97,ORD-0098,2026-06-26,Emre,Adana,Market,Zeytinyağı,Standart,Banka Kartı,540,1,0.05,513.0,4,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı
99,ORD-0100,2026-06-13,Efe,Eskişehir,Kitap,Kişisel Gelişim Kitabı,Standart,Havale,100,1,0.00,100.0,2,Tamamlandı

In [33]:
df[
    (df["uyelik_tipi"] == "Gold")
    &
    (df["toplam_tutar"] > 1000)
]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
16,ORD-0017,2026-06-01,Burak,Bursa,Elektronik,Bluetooth Kulaklık,Gold,Banka Kartı,1150,4,0.15,3910.0,1,Tamamlandı
20,ORD-0021,2026-05-31,Burak,İzmir,Elektronik,Kablosuz Mouse,Gold,Kapıda Ödeme,3000,4,0.10,10800.0,4,Tamamlandı
49,ORD-0050,2026-06-07,Aslı,Trabzon,Moda,Çanta,Gold,Kredi Kartı,1370,3,0.10,3699.0,3,Tamamlandı
57,ORD-0058,2026-05-21,Eylül,Adana,Kozmetik,Şampuan,Gold,Banka Kartı,1160,1,0.10,1044.0,3,Tamamlandı
71,ORD-0072,2026-05-18,İrem,Adana,Elektronik,Telefon Kılıfı,Gold,Kapıda Ödeme,2260,3,0.10,6102.0,7,Tamamlandı
78,ORD-0079,2026-05-18,Kerem,Antalya,Elektronik,Bluetooth Kulaklık,Gold,Kapıda Ödeme,1860,1,0.10,1674.0,3,Tamamlandı
88,ORD-0089,2026-05-11,Mehmet,Antalya,Moda,Ceket,Gold,Kapıda Ödeme,960,2,0.10,1728.0,2,Tamamlandı
90,ORD-0091,2026-06-06,Eylül,Konya,Elektronik,Powerbank,Gold,Kredi Kartı,2190,2,0.10,3942.0,3,Tamamlandı
94,ORD-0095,2026-06-18,Deniz,Adana,Moda,Çanta,Gold,Kapıda Ödeme,1750,1,0.10,1575.0,3,İade
96,ORD-0097,2026-06-10,Tuna,Muğla,Elektronik,Akıllı Saat,Gold,Kapıda Ödeme,1890,2,0.10,3402.0,3,Tamamlandı
98,ORD-0099,2026-06-11,Zeynep,İzmir,Kozmetik,Nemlendirici,Gold,Kapıda Ödeme,850,2,0.10,1530.0,3,Tamamlandı

In [34]:
df.groupby("uyelik_tipi")["toplam_tutar"].mean()

uyelik_tipi
Gold        2515.500000
Silver      1743.305556
Standart    1496.925532
Name: toplam_tutar, dtype: float64

In [35]:
tamamlanan_siparisler.groupby("kategori")["toplam_tutar"].sum().sort_values(ascending=False)

kategori
Elektronik    67428.5
Moda          23174.0
Kozmetik      22029.0
Market        18591.0
Oyuncak        8618.5
Kitap          7126.5
Spor           6948.0
Ev & Yaşam     4356.0
Name: toplam_tutar, dtype: float64

In [36]:
tamamlanan_siparisler.groupby("sehir")["toplam_tutar"].sum().sort_values(ascending=False)

sehir
Eskişehir    25195.5
Adana        21680.5
İzmir        19130.0
Antalya      19015.0
Konya        18021.5
Muğla        15341.0
Ankara       12969.5
Bursa        11071.0
İstanbul      9951.5
Trabzon       5896.0
Name: toplam_tutar, dtype: float64

In [38]:
df["siparis_durumu"].value_counts()

siparis_durumu
Tamamlandı    89
İptal          8
İade           3
Name: count, dtype: int64

In [39]:
df.groupby("kategori")["kargo_suresi_gun"].mean().sort_values(ascending=False)

kategori
Oyuncak       3.555556
Elektronik    3.277778
Kitap         3.000000
Ev & Yaşam    3.000000
Market        2.750000
Kozmetik      2.714286
Moda          2.687500
Spor          2.500000
Name: kargo_suresi_gun, dtype: float64

In [40]:
df.select_dtypes(include="number").corr()

,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun
urun_fiyati,1.000000,-0.000452,0.132856,0.764104,0.135641
adet,-0.000452,1.000000,-0.030251,0.513181,0.124418
indirim_orani,0.132856,-0.030251,1.000000,0.169830,0.034192
toplam_tutar,0.764104,0.513181,0.169830,1.000000,0.166860
kargo_suresi_gun,0.135641,0.124418,0.034192,0.166860,1.000000

**Genel Değerlendirme**

*   En güçlü ilişki ürün fiyatı ile toplam sipariş tutarı arasındadır. Korelasyon değeri 0.76 olduğu için aralarında güçlü bir ilişki olduğu söylenebilir.
*   Sipariş adedi de toplam sipariş tutarını etkileyen önemli faktörlerden biridir.

*   İndirim oranı ve kargo süresinin ise toplam sipariş tutarı üzerinde belirgin bir etkisi görünmemektedir.

In [41]:
df[df["toplam_tutar"] == df["toplam_tutar"].max()]

,siparis_id,siparis_tarihi,musteri_adi,sehir,kategori,urun,uyelik_tipi,odeme_yontemi,urun_fiyati,adet,indirim_orani,toplam_tutar,kargo_suresi_gun,siparis_durumu
20,ORD-0021,2026-05-31,Burak,İzmir,Elektronik,Kablosuz Mouse,Gold,Kapıda Ödeme,3000,4,0.1,10800.0,4,Tamamlandı

In [42]:
tamamlanan_siparisler.groupby("kategori")["toplam_tutar"].sum().sort_values(ascending=False).head(1)

kategori
Elektronik    67428.5
Name: toplam_tutar, dtype: float64

In [43]:
df.groupby("uyelik_tipi")["toplam_tutar"].mean().sort_values(ascending=False)

uyelik_tipi
Gold        2515.500000
Silver      1743.305556
Standart    1496.925532
Name: toplam_tutar, dtype: float64

In [45]:
tamamlanan_siparisler.groupby("sehir")["toplam_tutar"].sum().sort_values(ascending=False).head(1)

sehir
Eskişehir    25195.5
Name: toplam_tutar, dtype: float64

In [46]:
df["kargo_suresi_gun"].mean()

np.float64(2.92)

In [48]:
print("İçgörü 1: Ortalama sipariş tutarı yaklaşık 1759 TL'dir. Medyanın 1173 TL olması, bazı yüksek tutarlı siparişlerin ortalamayı artırdığını düşündürüyor.")

print("İçgörü 2: Tamamlanan siparişlerden elde edilen toplam ciro yaklaşık 158272 TL'dir.")

print("İçgörü 3: En fazla ciro Elektronik kategorisinden elde edilmiştir. Bu yüzden bu kategoriye daha fazla önem verilebilir.")

print("İçgörü 4: Gold üyelerin ortalama sipariş tutarı Standart üyelere göre daha yüksektir. Bu da üyelik seviyesinin harcama üzerinde etkili olabileceğini gösteriyor.")

print("İçgörü 5: Standart sapmanın yüksek olması, sipariş tutarlarının birbirinden farklı olduğunu gösteriyor. Bu nedenle müşterileri harcama miktarına göre gruplandırmak faydalı olabilir.")

İçgörü 1: Ortalama sipariş tutarı yaklaşık 1759 TL'dir. Medyanın 1173 TL olması, bazı yüksek tutarlı siparişlerin ortalamayı artırdığını düşündürüyor.
İçgörü 2: Tamamlanan siparişlerden elde edilen toplam ciro yaklaşık 158272 TL'dir.
İçgörü 3: En fazla ciro Elektronik kategorisinden elde edilmiştir. Bu yüzden bu kategoriye daha fazla önem verilebilir.
İçgörü 4: Gold üyelerin ortalama sipariş tutarı Standart üyelere göre daha yüksektir. Bu da üyelik seviyesinin harcama üzerinde etkili olabileceğini gösteriyor.
İçgörü 5: Standart sapmanın yüksek olması, sipariş tutarlarının birbirinden farklı olduğunu gösteriyor. Bu nedenle müşterileri harcama miktarına göre gruplandırmak faydalı olabilir.